id: hl7.fhir.fr.medication
canonical: https://hl7.fr/fhir/fr/medication
name: MED
title: Guide d'implémentation du médicament
publisher:
  name: Interop'Santé
  url: http://interopsante.org/
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build



dependencies:
  hl7.fhir.fr.core: 2.0.1

pages:
    index.md: 
      title: Accueil
    conciliation.md:
      title: La conciliation
    transformationPN13-FHIR.md:
      title: Transformation de PN13 en FHIR
    downloads.md:
      title: Téléchargements et usages
    suivitravaux.md:
      title: Historique des travaux


menu:
  Accueil: index.html
  Conciliation: 
      Introdution: conciliation-Intro.html
      Vue d'ensemble: conciliation-VueEnsemble.html
      Cas d'uasage: conciliation-CasUsage.html
      Ressources: conciliation-Ressources.html
      Implémentation: conciliation-Implementation.html
      Exemples: conciliation-Exemples.html
  Prescription:
      Introduction: prescription-Intro.html
      Vue d'ensemble: prescription-VueEnsemble.html
      Cas d'usage: prescription-CasUsage.html
      Ressources: prescription-Ressources.html
      Implémentation: prescription-Implementation.html
      Exemples: prescription-Exemples.html
      Etude complémentaire: prescription-EtudeComplementaire.html
  Dispensation:
      Introduction: dispensation-Intro.html
      Ressource *MedicationDispense*: dispensation-RessourceMedicationDispense.html
      La delivrance la plus simple: dispensation-DelivrancePlusSimple.html
      La dispensation nominative à délivrance reglobalisée: dispensation-DispensationNominativeDelivranceReglobalisee.html
      Discussion: dispensation-discussion.html
  Transformation PN13: transformationPN13-FHIR.html
  Ressources de conformité: artifacts.html
  Autres ressources:
      Historique des travaux: suivitravaux.html
      Téléchargements et usages: downloads.html
      "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
      "Site HL7 ": new-tab https://hl7.fr